<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class Employee extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('employee', function (Blueprint $table) {
            $table->bigIncrements('emp_id');
            $table->Integer('emp_type_id');
            $table->string('emp_code',10);
            $table->string('mobile_number',10);
            $table->string('service_id',20);
            $table->Integer('language_id');
            $table->string('full_name',32);
            $table->Integer('emp_role');
            $table->date('emp_dob');
            $table->string('birth_place',50);
            $table->Integer('emp_age');
            $table->Integer('emp_height');
            $table->Integer('emp_weight');
            $table->string('religion_title',32);
            $table->Integer('nationality_id');
            $table->Integer('sibling_no')->nullable();
            $table->string('sibling_age',10)->nullable();
            $table->longText('home_address');
            $table->string('airport_name',50);
            $table->Integer('marital_status');
            $table->Integer('child_count')->nullable();
            $table->string('child_age',10)->nullable();
            $table->string('expected_salary',5);
            $table->Integer('education_id');
            $table->string('emp_photo',50);
            $table->string('emp_full_photo',50)->nullable();
            $table->string('any_other_remark',100)->nullable();
            $table->Integer('rest_day')->nullable();
            $table->string('fwd_declaration',3)->nullable();
            $table->string('tel_interview_ea',3)->default('No');
            $table->string('video_interview_ea',3)->default('No');
            $table->string('person_interview_ea',3)->default('No');
            $table->string('observation_interview_ea',3)->default('No');
            $table->string('tel_interview_tr',3)->default('No');
            $table->string('video_interview_tr',3)->default('No');
            $table->string('person_interview_tr',3)->default('No');
            $table->string('observation_interview_tr',3)->default('No');
            $table->string('video_link');
            $table->string('work_prefrence',20)->nullable();
            $table->string('allergies_detail',100)->nullable();
            $table->string('disabilities_detail',100)->nullable();
            $table->string('dietary_detail',100)->nullable();
            $table->string('food_handling',5)->nullable();
            $table->string('food_handling_other',50)->nullable();
            $table->string('food_type_1',3)->default('No');
            $table->string('food_type_2',3)->default('No');
            $table->string('food_type_3',50)->nullable();
            $table->string('ill_no_1',3)->default('No');
            $table->string('ill_no_2',3)->default('No');
            $table->string('ill_no_3',3)->default('No');
            $table->string('ill_no_4',3)->default('No');
            $table->string('ill_no_5',3)->default('No');
            $table->string('ill_no_6',3)->default('No');
            $table->string('ill_no_7',3)->default('No');
            $table->string('ill_no_8',3)->default('No');
            $table->string('ill_no_9',3)->default('No');
            $table->string('existing_illnesses_other',50)->nullable();
            $table->string('fdw_no_interview',3)->default('No');
            $table->string('fdw_tel_interview',3)->default('No');
            $table->string('fdw_video_interview',3)->default('No');
            $table->string('fdw_per_interview',3)->default('No');
            $table->string('other_remark',100)->nullable();
            $table->string('ea_center',30)->nullable();
            $table->string('infants_age_sin',30)->nullable();
            $table->string('cooking_sin',30)->nullable();
            $table->string('language_sin',30)->nullable();
            $table->string('other_skill_sin',50)->nullable();
            $table->string('willing_sin_1',3)->nullable();
            $table->string('willing_sin_2',3)->nullable();
            $table->string('willing_sin_3',3)->nullable();
            $table->string('willing_sin_4',3)->nullable();
            $table->string('willing_sin_5',3)->nullable();
            $table->string('willing_sin_7',3)->nullable();
            $table->string('exp_sin_1',5)->nullable();
            $table->string('exp_sin_2',5)->nullable();
            $table->string('exp_sin_3',5)->nullable();
            $table->string('exp_sin_4',5)->nullable();
            $table->string('exp_sin_5',5)->nullable();
            $table->string('exp_sin_6',5)->nullable();
            $table->string('exp_sin_7',5)->nullable();
            $table->string('rat_sin_1',1)->nullable();
            $table->string('rat_sin_2',1)->nullable();
            $table->string('rat_sin_3',1)->nullable();
            $table->string('rat_sin_4',1)->nullable();
            $table->string('rat_sin_5',1)->nullable();
            $table->string('rat_sin_6',1)->nullable();
            $table->string('rat_sin_7',1)->nullable();
            $table->string('infants_age_ea',30)->nullable();
            $table->string('cooking_ea',30)->nullable();
            $table->string('language_ea',30)->nullable();
            $table->string('other_skill_ea',30)->nullable();
            $table->string('willing_ea_1',3)->nullable();
            $table->string('willing_ea_2',3)->nullable();
            $table->string('willing_ea_3',3)->nullable();
            $table->string('willing_ea_4',3)->nullable();
            $table->string('willing_ea_5',3)->nullable();
            $table->string('willing_ea_7',3)->nullable();
            $table->string('exp_ea_1',5)->nullable();
            $table->string('exp_ea_2',5)->nullable();
            $table->string('exp_ea_3',5)->nullable();
            $table->string('exp_ea_4',5)->nullable();
            $table->string('exp_ea_5',5)->nullable();
            $table->string('exp_ea_6',5)->nullable();
            $table->string('exp_ea_7',5)->nullable();
            $table->string('rat_ea_1',1)->nullable();
            $table->string('rat_ea_2',1)->nullable();
            $table->string('rat_ea_3',1)->nullable();
            $table->string('rat_ea_4',1)->nullable();
            $table->string('rat_ea_5',1)->nullable();
            $table->string('rat_ea_6',1)->nullable();
            $table->string('rat_ea_7',1)->nullable();
            $table->string('sing_exp',3)->default('No');
            $table->string('fdb_emp_1',50)->nullable();
            $table->string('fdb_dtl_1',150)->nullable();
            $table->string('fdb_emp_2',50)->nullable();
            $table->string('fdb_dtl_2',150)->nullable();
            $table->string('fdb_emp_3',50)->nullable();
            $table->string('fdb_dtl_3',150)->nullable();
            $table->date('start_date_1')->nullable();
            $table->date('end_date_1')->nullable();
            $table->string('country_dtl_1',50)->nullable();
            $table->string('emp_dtl_1',50)->nullable();
            $table->string('work_dtl_1',100)->nullable();
            $table->string('remark_dtl_1',100)->nullable();
            $table->date('start_date_2')->nullable();
            $table->date('end_date_2')->nullable();
            $table->string('country_dtl_2',50)->nullable();
            $table->string('emp_dtl_2',50)->nullable();
            $table->string('work_dtl_2',100)->nullable();
            $table->string('remark_dtl_2',100)->nullable();
            $table->date('start_date_3')->nullable();
            $table->date('end_date_3')->nullable();
            $table->string('country_dtl_3',50)->nullable();
            $table->string('emp_dtl_3',50)->nullable();
            $table->string('work_dtl_3',100)->nullable();
            $table->string('remark_dtl_3',100)->nullable();
            $table->softDeletes();
            $table->index(['emp_type_id','service_id','language_id','full_name','education_id','nationality_id'], 'employee_filter');
            $table->timestamp('created_at')->default(DB::raw('CURRENT_TIMESTAMP'));
            $table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP'));
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists("users");
    }
}
